using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Web;

namespace KoFFPanel.Infrastructure.Services;

public class ParsedProxy
{
    public string Protocol { get; set; } = "";
    public string Name { get; set; } = "";
    public string Server { get; set; } = "";
    public int Port { get; set; }
    public string UuidOrPassword { get; set; } = "";
    public Dictionary<string, string> Params { get; set; } = new(StringComparer.OrdinalIgnoreCase);
}

public static class SubscriptionConfigConverter
{
    public static ParsedProxy? ParseUri(string uriString)
    {
        if (string.IsNullOrWhiteSpace(uriString)) return null;

        try
        {
            string clean = uriString.Trim();
            int schemeIdx = clean.IndexOf("://", StringComparison.Ordinal);
            if (schemeIdx <= 0) return null;

            string scheme = clean[..schemeIdx].ToLowerInvariant();
            string remaining = clean[(schemeIdx + 3)..];

            // Extract fragment (#name)
            string tag = "";
            int hashIdx = remaining.IndexOf('#');
            if (hashIdx >= 0)
            {
                tag = Uri.UnescapeDataString(remaining[(hashIdx + 1)..]);
                remaining = remaining[..hashIdx];
            }

            // Extract query (?param=val)
            var queryParams = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            int queryIdx = remaining.IndexOf('?');
            if (queryIdx >= 0)
            {
                string queryStr = remaining[(queryIdx + 1)..];
                remaining = remaining[..queryIdx];

                foreach (var pair in queryStr.Split('&', StringSplitOptions.RemoveEmptyEntries))
                {
                    int eqIdx = pair.IndexOf('=');
                    if (eqIdx > 0)
                    {
                        string k = Uri.UnescapeDataString(pair[..eqIdx]);
                        string v = Uri.UnescapeDataString(pair[(eqIdx + 1)..]);
                        queryParams[k] = v;
                    }
                }
            }

            // Parse userInfo@host:port
            int atIdx = remaining.LastIndexOf('@');
            if (atIdx <= 0) return null;

            string userInfo = remaining[..atIdx];
            string hostPort = remaining[(atIdx + 1)..];

            string host;
            int port;

            if (hostPort.StartsWith('['))
            {
                int closeBracket = hostPort.IndexOf(']');
                if (closeBracket < 0) return null;
                host = hostPort[1..closeBracket];
                string portStr = hostPort[(closeBracket + 1)..].TrimStart(':');
                if (!int.TryParse(portStr, out port)) return null;
            }
            else
            {
                int colonIdx = hostPort.LastIndexOf(':');
                if (colonIdx < 0) return null;
                host = hostPort[..colonIdx];
                if (!int.TryParse(hostPort[(colonIdx + 1)..], out port)) return null;
            }

            if (string.IsNullOrWhiteSpace(tag))
            {
                tag = $"{scheme.ToUpperInvariant()}-{host}:{port}";
            }

            return new ParsedProxy
            {
                Protocol = scheme,
                Name = tag,
                Server = host,
                Port = port,
                UuidOrPassword = userInfo,
                Params = queryParams
            };
        }
        catch
        {
            return null;
        }
    }

    public static string GenerateClashYaml(IEnumerable<string> links, string title = "KoFFPanel")
    {
        var proxies = links.Select(ParseUri).Where(p => p != null).ToList()!;
        if (proxies.Count == 0)
        {
            return "# No proxies available\nproxies: []\nproxy-groups: []\nrules:\n  - MATCH,DIRECT\n";
        }

        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by KoFFPanel Universal Subscription Engine");
        sb.AppendLine($"port: 7890");
        sb.AppendLine($"socks-port: 7891");
        sb.AppendLine($"allow-lan: false");
        sb.AppendLine($"mode: rule");
        sb.AppendLine($"log-level: info");
        sb.AppendLine();
        sb.AppendLine("proxies:");

        var proxyNames = new List<string>();
        int idx = 1;

        foreach (var p in proxies)
        {
            string pName = $"{p!.Name} [{idx++}]".Replace("\"", "\\\"");
            proxyNames.Add(pName);

            sb.AppendLine($"  - name: \"{pName}\"");

            if (p.Protocol == "vless")
            {
                sb.AppendLine($"    type: vless");
                sb.AppendLine($"    server: \"{p.Server}\"");
                sb.AppendLine($"    port: {p.Port}");
                sb.AppendLine($"    uuid: \"{p.UuidOrPassword}\"");
                sb.AppendLine($"    network: tcp");
                sb.AppendLine($"    udp: true");

                if (p.Params.TryGetValue("flow", out var flow) && !string.IsNullOrEmpty(flow))
                {
                    sb.AppendLine($"    flow: \"{flow}\"");
                }

                if (string.Equals(p.Params.GetValueOrDefault("security"), "reality", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine($"    tls: true");
                    sb.AppendLine($"    servername: \"{p.Params.GetValueOrDefault("sni", "google.com")}\"");
                    sb.AppendLine($"    reality-opts:");
                    sb.AppendLine($"      public-key: \"{p.Params.GetValueOrDefault("pbk", "")}\"");
                    if (p.Params.TryGetValue("sid", out var sid))
                    {
                        sb.AppendLine($"      short-id: \"{sid}\"");
                    }
                    sb.AppendLine($"    client-fingerprint: \"{p.Params.GetValueOrDefault("fp", "chrome")}\"");
                }
            }
            else if (p.Protocol is "hy2" or "hysteria2")
            {
                sb.AppendLine($"    type: hysteria2");
                sb.AppendLine($"    server: \"{p.Server}\"");
                sb.AppendLine($"    port: {p.Port}");
                sb.AppendLine($"    password: \"{p.UuidOrPassword}\"");
                sb.AppendLine($"    sni: \"{p.Params.GetValueOrDefault("sni", "bing.com")}\"");
                sb.AppendLine($"    skip-cert-verify: true");
                sb.AppendLine($"    alpn:");
                sb.AppendLine($"      - h3");

                if (p.Params.TryGetValue("obfs", out var obfsType) && !string.IsNullOrEmpty(obfsType))
                {
                    sb.AppendLine($"    obfs: \"{obfsType}\"");
                    if (p.Params.TryGetValue("obfs-password", out var obfsPass))
                    {
                        sb.AppendLine($"    obfs-password: \"{obfsPass}\"");
                    }
                }
            }
            else if (p.Protocol == "trojan")
            {
                sb.AppendLine($"    type: trojan");
                sb.AppendLine($"    server: \"{p.Server}\"");
                sb.AppendLine($"    port: {p.Port}");
                sb.AppendLine($"    password: \"{p.UuidOrPassword}\"");
                sb.AppendLine($"    sni: \"{p.Params.GetValueOrDefault("sni", "bing.com")}\"");
                sb.AppendLine($"    skip-cert-verify: true");
                sb.AppendLine($"    udp: true");
            }
            else if (p.Protocol == "tuic")
            {
                string uuid = p.UuidOrPassword;
                string password = p.UuidOrPassword;
                int colonIdx = p.UuidOrPassword.IndexOf(':');
                if (colonIdx > 0)
                {
                    uuid = p.UuidOrPassword[..colonIdx];
                    password = p.UuidOrPassword[(colonIdx + 1)..];
                }

                sb.AppendLine($"    type: tuic");
                sb.AppendLine($"    server: \"{p.Server}\"");
                sb.AppendLine($"    port: {p.Port}");
                sb.AppendLine($"    uuid: \"{uuid}\"");
                sb.AppendLine($"    password: \"{password}\"");
                sb.AppendLine($"    sni: \"{p.Params.GetValueOrDefault("sni", "bing.com")}\"");
                sb.AppendLine($"    skip-cert-verify: true");
                sb.AppendLine($"    congestion-controller: \"{p.Params.GetValueOrDefault("congestion_control", "bbr")}\"");
                sb.AppendLine($"    alpn:");
                sb.AppendLine($"      - h3");
            }
            else
            {
                // Fallback for generic/unsupported
                sb.AppendLine($"    type: vless");
                sb.AppendLine($"    server: \"{p.Server}\"");
                sb.AppendLine($"    port: {p.Port}");
                sb.AppendLine($"    uuid: \"{p.UuidOrPassword}\"");
            }
        }

        sb.AppendLine();
        sb.AppendLine("proxy-groups:");

        // 1. Selector group
        sb.AppendLine("  - name: \"🚀 PROXY\"");
        sb.AppendLine("    type: select");
        sb.AppendLine("    proxies:");
        sb.AppendLine("      - \"🔄 AUTO - Самый быстрый\"");
        sb.AppendLine("      - \"🛡️ РЕЗЕРВ - Failover\"");
        foreach (var name in proxyNames)
        {
            sb.AppendLine($"      - \"{name}\"");
        }
        sb.AppendLine("      - DIRECT");

        // 2. Auto fastest group
        sb.AppendLine("  - name: \"🔄 AUTO - Самый быстрый\"");
        sb.AppendLine("    type: url-test");
        sb.AppendLine("    url: http://www.gstatic.com/generate_204");
        sb.AppendLine("    interval: 300");
        sb.AppendLine("    tolerance: 50");
        sb.AppendLine("    proxies:");
        foreach (var name in proxyNames)
        {
            sb.AppendLine($"      - \"{name}\"");
        }

        // 3. Fallback failover group
        sb.AppendLine("  - name: \"🛡️ РЕЗЕРВ - Failover\"");
        sb.AppendLine("    type: fallback");
        sb.AppendLine("    url: http://www.gstatic.com/generate_204");
        sb.AppendLine("    interval: 300");
        sb.AppendLine("    proxies:");
        foreach (var name in proxyNames)
        {
            sb.AppendLine($"      - \"{name}\"");
        }

        sb.AppendLine();
        sb.AppendLine("rules:");
        sb.AppendLine("  - MATCH,🚀 PROXY");

        return sb.ToString();
    }

    public static string GenerateSingBoxJson(IEnumerable<string> links, string title = "KoFFPanel")
    {
        var proxies = links.Select(ParseUri).Where(p => p != null).ToList()!;

        var outbounds = new JsonArray();
        var proxyTags = new List<string>();
        int idx = 1;

        foreach (var p in proxies)
        {
            string tag = $"{p!.Name} [{idx++}]";
            proxyTags.Add(tag);

            if (p.Protocol == "vless")
            {
                var vlessObj = new JsonObject
                {
                    ["type"] = "vless",
                    ["tag"] = tag,
                    ["server"] = p.Server,
                    ["server_port"] = p.Port,
                    ["uuid"] = p.UuidOrPassword
                };

                if (p.Params.TryGetValue("flow", out var flow) && !string.IsNullOrEmpty(flow))
                {
                    vlessObj["flow"] = flow;
                }

                if (string.Equals(p.Params.GetValueOrDefault("security"), "reality", StringComparison.OrdinalIgnoreCase))
                {
                    vlessObj["tls"] = new JsonObject
                    {
                        ["enabled"] = true,
                        ["server_name"] = p.Params.GetValueOrDefault("sni", "google.com"),
                        ["reality"] = new JsonObject
                        {
                            ["enabled"] = true,
                            ["public_key"] = p.Params.GetValueOrDefault("pbk", ""),
                            ["short_id"] = p.Params.GetValueOrDefault("sid", "")
                        },
                        ["utls"] = new JsonObject
                        {
                            ["enabled"] = true,
                            ["fingerprint"] = p.Params.GetValueOrDefault("fp", "chrome")
                        }
                    };
                    vlessObj["packet_encoding"] = "xudp";
                }

                outbounds.Add(vlessObj);
            }
            else if (p.Protocol is "hy2" or "hysteria2")
            {
                var hy2Obj = new JsonObject
                {
                    ["type"] = "hysteria2",
                    ["tag"] = tag,
                    ["server"] = p.Server,
                    ["server_port"] = p.Port,
                    ["password"] = p.UuidOrPassword,
                    ["tls"] = new JsonObject
                    {
                        ["enabled"] = true,
                        ["server_name"] = p.Params.GetValueOrDefault("sni", "bing.com"),
                        ["insecure"] = true,
                        ["alpn"] = new JsonArray { "h3" }
                    }
                };

                if (p.Params.TryGetValue("obfs", out var obfsType) && !string.IsNullOrEmpty(obfsType))
                {
                    hy2Obj["obfs"] = new JsonObject
                    {
                        ["type"] = obfsType,
                        ["password"] = p.Params.GetValueOrDefault("obfs-password", "")
                    };
                }

                outbounds.Add(hy2Obj);
            }
            else if (p.Protocol == "trojan")
            {
                outbounds.Add(new JsonObject
                {
                    ["type"] = "trojan",
                    ["tag"] = tag,
                    ["server"] = p.Server,
                    ["server_port"] = p.Port,
                    ["password"] = p.UuidOrPassword,
                    ["tls"] = new JsonObject
                    {
                        ["enabled"] = true,
                        ["server_name"] = p.Params.GetValueOrDefault("sni", "bing.com"),
                        ["insecure"] = true
                    }
                });
            }
            else if (p.Protocol == "tuic")
            {
                string uuid = p.UuidOrPassword;
                string password = p.UuidOrPassword;
                int colonIdx = p.UuidOrPassword.IndexOf(':');
                if (colonIdx > 0)
                {
                    uuid = p.UuidOrPassword[..colonIdx];
                    password = p.UuidOrPassword[(colonIdx + 1)..];
                }

                outbounds.Add(new JsonObject
                {
                    ["type"] = "tuic",
                    ["tag"] = tag,
                    ["server"] = p.Server,
                    ["server_port"] = p.Port,
                    ["uuid"] = uuid,
                    ["password"] = password,
                    ["congestion_control"] = p.Params.GetValueOrDefault("congestion_control", "bbr"),
                    ["tls"] = new JsonObject
                    {
                        ["enabled"] = true,
                        ["server_name"] = p.Params.GetValueOrDefault("sni", "bing.com"),
                        ["insecure"] = true,
                        ["alpn"] = new JsonArray { "h3" }
                    }
                });
            }
        }

        // Add auto/fallback groups
        if (proxyTags.Count > 0)
        {
            var autoOutbound = new JsonObject
            {
                ["type"] = "urltest",
                ["tag"] = "auto",
                ["outbounds"] = new JsonArray(proxyTags.Select(t => (JsonNode)JsonValue.Create(t)!).ToArray()),
                ["url"] = "http://www.gstatic.com/generate_204",
                ["interval"] = "3m"
            };

            var selectOutbounds = new List<string> { "auto" };
            selectOutbounds.AddRange(proxyTags);
            selectOutbounds.Add("direct");

            var selectOutbound = new JsonObject
            {
                ["type"] = "selector",
                ["tag"] = "select",
                ["outbounds"] = new JsonArray(selectOutbounds.Select(t => (JsonNode)JsonValue.Create(t)!).ToArray()),
                ["default"] = "auto"
            };

            outbounds.Insert(0, selectOutbound);
            outbounds.Insert(1, autoOutbound);
        }

        outbounds.Add(new JsonObject { ["type"] = "direct", ["tag"] = "direct" });
        outbounds.Add(new JsonObject { ["type"] = "block", ["tag"] = "block" });

        var root = new JsonObject
        {
            ["log"] = new JsonObject { ["disabled"] = true },
            ["inbounds"] = new JsonArray(),
            ["outbounds"] = outbounds,
            ["route"] = new JsonObject { ["final"] = "select" }
        };

        return root.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
    }
}
